services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:latest
    profiles: ["phase2"]
  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:latest
    profiles: ["phase2"]
