name: docker

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: docker compose -f chain/docker/docker-compose.devnet.yml config
